### ISSUE TITLE
Vein miner

### ISSUE THREAD

**Issue by MunchNStuff** [ResqDiver1317/AdultCraft-Foundations#11]
Not working properly. Check configs and assess the issue. May just be an issue of conflict with tinkers.

**Comment by ResqDiver1317** [comment]
This is a limitation of the mod. Already set for max of 64 blocks to be broken at once, but the core factor is the mod monitors TPS while mining. When you break a lot of blocks at once, AdamantineShield has to log all that which causes TPS to go down. The mod sees the TPS start dropping and stops the Excavation Process
