### ISSUE TITLE
JAM not persisting

### ISSUE THREAD

**Issue by MunchNStuff** [ResqDiver1317/AdultCraft-Foundations#12]
/fly not persisting after death or upon entering the nether. 

JAM as well... possible config for default toggle=true

**Comment by ResqDiver1317** [comment]
This is expected behavior for the /fly. It's an anti-cheat thing
The JAM I'll take a look at and see.

**Comment by ResqDiver1317** [comment]
Need more details on this issue with JAM to see if this is a bug we need to report to the dev. The only config options are pickup range and speed picked up items will come to you.

**Comment by ResqDiver1317** [comment]
The anticheat functions is what is getting involved in this. There is not a solution to fix it as it's not a bug that Sponge or JaM Devs are concerned about.
