### ISSUE TITLE
Clear lag timer

### ISSUE THREAD

**Issue by GoddessTT** [ResqDiver1317/AdultCraft-Foundations#19]
Check that clear lag did not revert back to 10 min with msg of 60/30 sec vs 15 min (was giving 330 sec msg).

**Comment by ResqDiver1317** [comment]
LOL My bad, I forgot to tell you that I had fixed the countdown to give the 60/30 message on the 15min timer. Clearlags settings count up to the messages (540/570 seconds for a 10 minutes (600sec) timer gives 60/30 warnings. When I set the 15min/900 sec timer, I forgot to add time to the warning timers at first. I did it last night and it applied after restart.

**Comment by GoddessTT** [comment]
Thanks! I was like did it revert or ... lol
