### ISSUE TITLE
/RTP

### ISSUE THREAD

**Issue by GoddessTT** [ResqDiver1317/AdultCraft-Foundations#23]
Check /rtp it is sending people off the map and into water and caves again.

**Comment by ResqDiver1317** [comment]
I think this is a lag issue with the cascading world gen. Pregen is running so will leave this open for now and see how it performs once it's all done. Could also be a config issue if the config reset during a lag spike/restart, but most likely, simply lag related.

**Comment by ResqDiver1317** [comment]
Seems to have been Lag related. Does not appear to have issues now since the reset/pregen.
