### ISSUE TITLE
Modded trees/parts reverting to vanilla - Reported by JellieBaby

### ISSUE THREAD

**Issue by ResqDiver1317** [ResqDiver1317/AdultCraft-Foundations#25]
My Ethereal Saps turn into Oak Wood Trees, And My Natura Willow wood will not change into Willow wood sticks needed to make Willow Wood Fence. Is there anything I can do to fix this and get at least one of these pretty green woods to work with me?

--Will investigate once worldgen is done.

**Comment by GoddessTT** [comment]
So I tested this yesterday, I had a flowering oak planted, it grew, and I got oak saplings not flowering oak saplings. The trunk of the tree was oak, the leaves were flowering oak leaves, but again no flowering oak saplings just oak and oak wood.

**Comment by ResqDiver1317** [comment]
This is resolved thanks to NMRC, but only in vanilla tables, not in Tinkers stations.
