### ISSUE TITLE
check chunk around  x=-49, y=66, z=-1600

### ISSUE THREAD

**Issue by GoddessTT** [ResqDiver1317/AdultCraft-Foundations#29]
IUMA and I both got an error trying to pass this area. There is a HUGE fucking mountain, along with I think a smaller in front of it, it dc's you before you get there. 

Error msg, confirmed by me also to be the same one.
"Internal exception: io.netty.handler.codec.DecoderException: Badly compressed packet - size of 2964971 is larger then protocol maximum of 2097152"

**Comment by ResqDiver1317** [comment]
There is a chance this is an issue with stuff at Stephen's place, but unsure. Munch may look into it this weekend and I can look at it more Sunday when I get home.

**Comment by GoddessTT** [comment]
This has been dealt with, Stephen moved willingly (wanted a bigger island). Munch took out the area, and we filled it up with water. This is complete.
